const state={context:{},history:[],tool:'auto',lastRequest:null};
const el=id=>document.getElementById(id);
const api=()=> (localStorage.getItem('COPILOT_API')||'http://localhost:8000').replace(/\/$/,'');
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function md(text){let s=esc(text||''),blocks=[];s=s.replace(/```(?:dataweave|dw|json|xml|raml|yaml|sql|munit|java|properties|text)?\s*([\s\S]*?)```/gi,(_,c)=>{const t=`@@C${blocks.length}@@`;blocks.push(`<pre><code>${c.trim()}</code></pre>`);return t});s=s.replace(/`([^`]+)`/g,'<code>$1</code>').replace(/^### (.*)$/gm,'<h3>$1</h3>').replace(/^## (.*)$/gm,'<h3>$1</h3>').replace(/^# (.*)$/gm,'<h3>$1</h3>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>');s=`<p>${s}</p>`;blocks.forEach((x,i)=>s=s.replace(`@@C${i}@@`,x));return s}
function addMessage(role,text,meta='',data=null){const item=document.createElement('article');item.className=`message ${role}`;const verified=data?.verified===true,failed=data?.validation==='provider_error';let badges='';if(role==='assistant'&&data){badges=`<div class="result-strip"><span class="badge">Agent: ${esc(data.agent||'copilot')}</span><span class="badge">${Math.round((Number(data.confidence)||0)*100)}% confidence</span><span class="badge ${verified?'ok':failed?'warn':''}">${esc(data.validation||'generated')}</span>${data.attempts!=null?`<span class="badge">${data.attempts} attempt(s)</span>`:''}</div><div class="actions"><button class="mini" data-copy="1">Copy response</button><button class="mini" data-retry="1">Run again</button></div>`}item.innerHTML=`<div class="role-row"><div class="avatar">${role==='user'?'YOU':'AI'}</div><div><div class="role">${role==='user'?'You':'MuleSoft Copilot'}</div><div class="meta">${esc(meta)}</div></div></div><div class="bubble">${role==='assistant'?md(text):`<p>${esc(text).replace(/\n/g,'<br>')}</p>`}</div>${badges}`;el('thread').appendChild(item);el('messages').scrollTop=el('messages').scrollHeight;item.querySelector('[data-copy]')?.addEventListener('click',()=>navigator.clipboard?.writeText(text));item.querySelector('[data-retry]')?.addEventListener('click',()=>{if(state.lastRequest){el('prompt').value=state.lastRequest.message;run()}})}
function status(label,mode=''){el('status').textContent=label;el('dot').className=`dot ${mode}`}
function context(){return {...state.context,tool:state.tool,conversation:state.history.slice(-10).map(x=>({user:x.input,assistant:x.output?.answer||''}))}}
function parse(v){if(!v.trim())return null;try{return JSON.parse(v)}catch{return v}}
function drawer(title='Execution context'){el('drawerTitle').textContent=title;el('drawer').classList.add('open')}
function applyContext(){const i=el('inputPayload').value.trim(),o=el('expectedOutput').value.trim(),x=el('extraContext').value.trim();state.context={...state.context,...(i?{input:parse(i)}:{}),...(o?{expectedOutput:parse(o)}:{}),inputMimeType:el('inputMime').value,...(x?{additionalContext:x}:{})};updateContext();el('drawer').classList.remove('open')}
function updateContext(){const b=el('contextBar');const chips=[];if(state.context.input!==undefined)chips.push('<span class="chip">✓ Input</span>');if(state.context.expectedOutput!==undefined)chips.push('<span class="chip">✓ Expected</span>');if(state.context.additionalContext)chips.push('<span class="chip">✓ Code/log</span>');b.innerHTML=`<button class="attach" id="inputBtn">＋ Input payload</button><button class="attach" id="expectedBtn">＋ Expected output</button><button class="attach" id="fileBtn">＋ Code / log</button><button class="attach" id="filePickBtn">＋ Attach file</button>${chips.join('')}`;el('inputBtn').onclick=()=>drawer('Input payload');el('expectedBtn').onclick=()=>drawer('Expected output');el('fileBtn').onclick=()=>drawer('Code / log / context');el('filePickBtn').onclick=()=>el('fileInput').click()}
function tool(t){state.tool=t;document.querySelectorAll('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));const n={auto:'Auto · routes natural-language requests to the right MuleSoft capability',dataweave:'DataWeave · generate, execute, repair and verify',debug:'Debugger · evidence, root cause and safe fixes',raml:'API / RAML · contracts, types and examples',flow:'Mule Flow · XML, connectors and architecture',munit:'MUnit · tests, mocks and assertions',sql:'SQL / DB · Snowflake and database work'};el('modeLabel').textContent=n[t]||n.auto}
async function check(){try{const r=await fetch(api()+'/docs',{cache:'no-store'});if(r.ok)status('Backend connected','ok');else status('Backend unavailable','bad')}catch{status('Backend unavailable','bad')}}
function providerError(d){const raw=String(d?.answer||d?.detail||d?.error||'');if(/429|rate_limit_exceeded|tokens per day|TPD/i.test(raw))return `**AI provider rate limit reached**\n\nThe MuleSoft Copilot frontend and backend are connected, but the configured AI provider has exhausted its current token quota. This is not a frontend transformation error.\n\n**What you can do now:**\n- Wait for the provider quota window to reset, then use **Run again**.\n- Configure a provider/model with available quota in the backend environment.\n- Real DataWeave execution is separate from the AI provider and can still be used when a request reaches the executor.`;return raw}
async function run(){const input=el('prompt').value.trim();if(!input||el('run').disabled)return;state.lastRequest={message:input};addMessage('user',input,state.tool==='auto'?'Auto mode':`${state.tool} mode`);el('prompt').value='';el('count').textContent='0';el('run').disabled=true;status('Thinking…','busy');try{const payload={message:input,context:context()};const r=await fetch(api()+'/api/v1/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let d;try{d=await r.json()}catch{throw new Error(`Backend returned HTTP ${r.status}`)}if(!r.ok)throw new Error(d.detail||d.error||`Request failed (${r.status})`);state.history.push({input,output:d});const isProvider=d.validation==='provider_error'||/429|rate_limit_exceeded|tokens per day/i.test(String(d.answer||''));if(isProvider)d={...d,answer:providerError(d),validation:'provider_error',verified:false};addMessage('assistant',d.answer||'No answer returned.',d.verified?'Verified result':isProvider?'Provider quota issue':'Generated result',d);status(d.verified?'Verified result':isProvider?'Provider quota issue':'Generated result',d.verified?'ok':isProvider?'bad':'')}catch(e){const msg=String(e.message||e);const is429=/429|rate_limit/i.test(msg);addMessage('assistant',is429?providerError({answer:msg}):`**Request failed**\n\n${msg}`,'Request failed',{validation:is429?'provider_error':'request_error',confidence:0});status(is429?'Provider quota issue':'Request failed','bad')}finally{el('run').disabled=false;el('prompt').focus()}}
function newChat(){state.history=[];state.context={};state.lastRequest=null;el('thread').innerHTML='';const w=document.createElement('div');w.className='welcome';w.id='welcome';w.innerHTML='<div class="eyebrow">MuleSoft engineering workspace</div><h1>Build. Execute. Verify. Repair.</h1><p>Start a new natural-language request. Add payload, expected output, code, logs or a file when relevant.</p>';el('thread').appendChild(w);updateContext();status('Ready');el('prompt').focus()}
el('run').onclick=run;el('newChat').onclick=newChat;el('clearChat').onclick=newChat;el('mobileNew').onclick=newChat;el('contextBtn').onclick=()=>drawer();el('closeDrawer').onclick=()=>el('drawer').classList.remove('open');el('saveContext').onclick=applyContext;document.querySelectorAll('.tool[data-tool]').forEach(b=>b.onclick=()=>tool(b.dataset.tool));document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{el('prompt').value=b.dataset.prompt;el('prompt').focus()});el('prompt').oninput=()=>el('count').textContent=el('prompt').value.length;el('prompt').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();run()}};el('fileInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const text=await f.text();state.context={...state.context,additionalContext:`Attached file: ${f.name}\n\n${text}`};updateContext();status(`Attached ${f.name}`,'ok');e.target.value=''};el('api').value=api();el('api').onchange=()=>{localStorage.setItem('COPILOT_API',el('api').value.replace(/\/$/,''));check()};updateContext();tool('auto');check();
